# Generated by Django 5.2.4 on 2025-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('msg', models.JSONField(blank=True, default=[{'content': 'You are a helpful assistant.', 'role': 'user'}], null=True)),
            ],
        ),
    ]
