# Generated by Django 5.2.4 on 2025-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('msg', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('girlfriend', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=100, null=True)),
                ('settings', models.JSONField(blank=True, default={'language': 'bangla', 'personality': 'flirty', 'pronoun': 'তুমি', 'theme': 'romantic', 'useEmojis': 'auto'}, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_location', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
