# Generated by Django 5.2.4 on 2025-07-29 14:13

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('api_key_index', models.IntegerField(default=0)),
                ('models_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'API Request',
                'verbose_name_plural': 'API Requests',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('messages', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('girlfriend', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=100, null=True)),
                ('settings', models.JSONField(default=chat.models.Usr.default_usr_settings)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_location', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Msg',
        ),
        migrations.AddField(
            model_name='apirequest',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_requests', to='chat.usr'),
        ),
    ]
