# Generated by Django 5.2.4 on 2025-07-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='msg',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='girlfriend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
