# Generated by Django 5.2.4 on 2025-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_msg_options_msg_gender_msg_girlfriend_msg_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='msg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
