# Generated by Django 5.2.4 on 2025-07-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_apirequest_usr_delete_msg_apirequest_usr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='models_name',
            new_name='model_name',
        ),
    ]
